name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Client and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client sshpass

      - name: SSH into Google Cloud VM
        run: |
          sshpass -p "Epoch@3" ssh -o StrictHostKeyChecking=no root@35.203.60.186 << EOF
            cd ../home/epoch
            rm -rf epoch_backend epoch_frontend
            sudo fuser -k -n tcp 443
            sudo fuser -k -n tcp 8080
            git clone https://github.com/Aymanhki/Epoch.git ./
            cd epoch/epoch_backend/
            docker build -t epoch_backend ./
            docker run -d -p 8080:8080 epoch_backend
            cd ..
            cd epoch/epoch_frontend
            docker build -t epoch_frontend ./
            docker run -d -p 443:443 epoch_frontend
            exit
          EOF
